[package]
name = "progenitor-macro"
version = "0.2.1-dev"
edition = "2021"
license = "MPL-2.0"
repository = "https://github.com/oxidecomputer/progenitor.git"
description = "An OpenAPI client generator - macros"

[dependencies]
openapiv3 = { workspace = true }
proc-macro2 = { workspace = true }
progenitor-impl = { workspace = true }
quote = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_tokenstream = "0.1.3"
syn = "1.0"

[lib]
proc-macro = true
