[package]
name = "example-macro"
version = "0.0.1"
authors = ["Adam H. Leventhal <ahl@oxidecomputer.com>"]
edition = "2021"

[dependencies]
chrono = { workspace = true }
progenitor = { workspace = true }
reqwest = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true,  features = ["derive"] }
uuid = { workspace = true }
