[package]
name = "progenitor"
version = "0.2.1-dev"
edition = "2021"
license = "MPL-2.0"
repository = "https://github.com/oxidecomputer/progenitor.git"
description = "An OpenAPI client generator"

[dependencies]
progenitor-client = { workspace = true }
progenitor-impl = { workspace = true }
progenitor-macro = { version = "0.2.1-dev", path = "../progenitor-macro" }
anyhow = "1.0"
openapiv3 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
clap = { version = "3.2.22", features = ["derive"] }

[dev-dependencies]
chrono = { workspace = true }
futures = "0.3.21"
percent-encoding = "2.2"
regress = "0.4.1"
reqwest = { workspace = true }
schemars = { workspace = true }
uuid = { workspace = true }
