[package]
name = "progenitor-client"
version = "0.2.1-dev"
edition = "2021"
license = "MPL-2.0"
repository = "https://github.com/oxidecomputer/progenitor.git"
description = "An OpenAPI client generator - client support"

[dependencies]
bytes = "1.2.1"
futures-core = "0.3.24"
percent-encoding = "2.2"
reqwest = { workspace = true, default-features = false }
serde = { workspace = true }
serde_json = { workspace = true }
serde_urlencoded = "0.7.1"
